wen-gong/week5/music-db/config/routes.rb
Rails.application.routes.draw do
  

   root to: 'albums#home'

   get '/albums/new' => 'albums#new', as: 'new_album'

   post '/albums' => 'albums#create'

   get '/albums' => 'albums#index'

   get '/albums/:id' => 'albums#show', as: 'album'

   get '/albums/:id/edit' => 'albums#edit', as: 'edit_album'


   patch '/albums/:id' => 'albums#update'

   get '/albums/:id/delete' => 'albums#destroy', as: 'destroy_album'


end

wen-gong/week5/music-db/app/models/album.rb
class Album < ApplicationRecord

end

wen-gong/week5/music-db/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def home
    end

    def new
        @album = Album.new

    end

    def create
        Album.create(
            name: params[:album][:name],
            released: params[:album][:released],
            genre: params[:album][:genre],
            length: params[:album][:length],
            image_url: params[:album][:image_url]

        )

        redirect_to albums_path 
    end

    def index
        @albums = Album.all

        # raise 'hell'

    end

    def show
        @album = Album.find params[:id]
    end

    def edit
        @album = Album.find params[:id]
    end

    def update
        album = Album.find params[:id]

        album.update(
            name: params[:album][:name],
            released: params[:album][:released],
            genre: params[:album][:genre],
            length: params[:album][:length],
            image_url: params[:album][:image_url]
        )

        redirect_to album_path(album.id)
    end

    def destroy
        Album.destroy params[:id]
        redirect_to albums_path
    end

end

wen-gong/week5/music-db/app/views/albums/edit.html.erb
<h2>Editing<%= @album.name %></h2>

<%= form_with model: @album, local: true do |f| %>

   <%= f.label :name %>
   <%= f.text_field :name %>
   <br>
  
   <%= f.label :released %>
   <%= f.text_field :released %>
   <br>

   <%= f.label :genre %>
   <%= f.text_field :genre %>
   <br>

   <%= f.label :length %>
   <%= f.text_field :length %>
   <br>

   <%= f.label :image_url %>
   <%= f.text_field :image_url %>
   <br>

   <%= f.submit 'Update Album' %>
   


<% end %>

wen-gong/week5/music-db/app/views/albums/home.html.erb
<h2>Your Tour of the Solar System Begins Here</h2>

wen-gong/week5/music-db/app/views/albums/index.html.erb
<h3>All Albums</h3>

<ul>
 <% @albums.each do |album| %>
    <li>
    
     <%= link_to album.name, planet_path(album.id) %>
    </li>
 <% end %>


</ul>

wen-gong/week5/music-db/app/views/albums/new.html.erb
<h2>Add New Album</h2>

<%= form_with model: @album, local: true do |f| %>

   <%= f.label :name %>
   <%= f.text_field :name %>
   <br>
  
   <%= f.label :released %>
   <%= f.text_field :released %>
   <br>

   <%= f.label :genre %>
   <%= f.text_field :genre %>
   <br>

   <%= f.label :length %>
   <%= f.text_field :length %>
   <br>

   <%= f.label :image_url %>
   <%= f.text_field :image_url %>
   <br>

   <%= f.submit 'Update Album' %>
   


<% end %>

wen-gong/week5/music-db/app/views/albums/show.html.erb
<h2><%= @album.name %></h2>

<%= link_to 'Edit', edit_album_path(@album.id) %>
<%= link_to 'Delete', destroy_album_path(@album.id) %>


<p>
  <strong>Released:</strong>
  <%= @album.mass %> released
</p>


<p>
  <strong>Genre:</strong>
  <%= @album.orbit %> genre
</p>


<p>
  <strong>Length:</strong>
  <%= @album.length %> 
</p>

<%= image_tag @album.image_url, alt: @album.name %>