mohamad-dakdouk/week5/wed/D23-countries-cities-hm/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get '/countries' => 'countries#home'

# Create
# 1. Blank form
get '/countries/new' => 'countries#new', as:'new_country'

# 2. Form Submits
post '/countries' => 'countries#create'

# Read
# 1. Index
get '/countries/index' => 'countries#index'

# 2. Show Details
get '/countries/:id' => 'countries#show', as: 'country'

# Update
# 1. Prefilled form
get '/countries/:id/edit' => 'countries#edit', as: 'edit_country'

# 2. Form submits
patch '/countries/:id' => 'countries#update'

# Delete
get 'countries/:id/delete' => 'countries#destroy', as:'destroy_country'

##################### Cities CRUD
resources :cities


end

mohamad-dakdouk/week5/wed/D23-countries-cities-hm/app/models/city.rb
class City < ApplicationRecord
    belongs_to :country
end

mohamad-dakdouk/week5/wed/D23-countries-cities-hm/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
    @city = City.new
  end

  def create
    City.create! city_params
    redirect_to cities_path
  end

  def index
    @cities = City.all
  end

  def show
    @city = City.find params[:id]
  end

  def edit
    @city = City.find params[:id]
  end

  def update
    city = City.find params[:id]
    city.update city_params
    redirect_to city_path(city.id)
  end

  def destroy
  end

  private 
  def city_params
    params.require(:city).permit( :name, :captial, :population, :attractions, :image, :country_id )
  end

end

mohamad-dakdouk/week5/wed/D23-countries-cities-hm/app/controllers/countries_controller.rb
class CountriesController < ApplicationController

def home

end


#create
def new
    @countries = Country.new

end

def create

    Country.create(
            name: params[:country][:name],
            location: params[:country][:location],
            language: params[:country][:language],
            population: params[:country][:population],
            vist: params[:country][:vist],
            image_url: params[:country][:image_url]
    )
    redirect_to countries_index_path
end

#read
def index
    @countries = Country.all
end

def show
    @countries = Country.find params[:id]
end

#update
def edit
    @countries = Country.find params[:id]

end

def update
    country = Country.find params[:id]
  country.update(
            name: params[:country][:name],
            location: params[:country][:location],
            language: params[:country][:language],
            population: params[:country][:population],
            vist: params[:country][:vist],
            image_url: params[:country][:image_url]
    )
    redirect_to country_path(country.id)

end 

def destroy
    Country.destroy params[:id]
    redirect_to country_path
end


end

mohamad-dakdouk/week5/wed/D23-countries-cities-hm/app/controllers/country.rb
class Country < ApplicationRecord
    has_many :cities

end

mohamad-dakdouk/week5/wed/D23-countries-cities-hm/app/helpers/cities_helper.rb
module CitiesHelper
end

mohamad-dakdouk/week5/wed/D23-countries-cities-hm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D23Countries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
      <nav>
        <h1>Tour of the World</h1>
        <%= link_to 'Home', '/countries' %>
        |
        <%= link_to 'All Countries', '/countries/index' %>
        |
        <%= link_to 'Add Country', '/countries/new' %>
        |
        <%= link_to 'All Cities', cities_path %>
        |
        <%= link_to 'Add City', new_city_path %>


       </nav>
      </nav>
    <%= yield %>
  </body>
</html>